# API 1 Scenario 1
GET http://localhost:3000/todos/?status=TO%20DO

###

# API 1 Scenario 2
GET http://localhost:3000/todos/?priority=HIGH

###


# API 1 Scenario 3
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###


# API 1 Scenario 4
GET http://localhost:3000/todos/?search_q=Buy

###


# API 1 Scenario 5
GET http://localhost:3000/todos/?category=WORK&status=DONE

###


# API 1 Scenario 6
GET http://localhost:3000/todos/?category=HOME

###


# API 1 Scenario 7
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH

###


# API 2 
GET http://localhost:3000/todos/8/

###


# API 3
GET http://localhost:3000/agenda/?date=2020-09-22

###


# API 4
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 9,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}

###


# API 5 Scenario 1
PUT http://localhost:3000/todos/5
Content-Type: application/json

{
    "status": "DONE"
}

###


# API 5 Scenario 2
PUT http://localhost:3000/todos/2
Content-Type: application/json

{
    "priority": "HIGH"
}

###


# API 5 Scenario 3
PUT http://localhost:3000/todos/4
Content-Type: application/json

{
    "todo": "Clean the garden"
}

###


# API 5 Scenario 4
PUT http://localhost:3000/todos/2
Content-Type: application/json

{
    "category": "LEARNING"
}

###


# API 5 Scenario 5
PUT http://localhost:3000/todos/8
Content-Type: application/json

{
    "dueDate": "2021-01-12"
}

###


# API 6
DELETE http://localhost:3000/todos/6

